export const CREW = [
  { id: "anvil", name: "Anvil", role: "Breacher", stat: "force", bonus: 5, color: "#ff5d4e", tagline: "Locks are just problems that haven't met me yet." },
  { id: "cipher", name: "Cipher", role: "Netrunner", stat: "hack", bonus: 5, color: "#4bf6cc", tagline: "Every system lies to someone. I just ask nicely first." },
  { id: "silk", name: "Silk", role: "Face", stat: "charm", bonus: 5, color: "#c77dff", tagline: "Nobody remembers the person who let them win the argument." },
];

export const SCENES = [
  {
    id: "lobby",
    floor: 1,
    kicker: "GROUND FLOOR / AFTER HOURS",
    title: "Through the Front Glass",
    description: "Midnight in the financial district. The Meridian's lobby is dark glass and dead monitors — Cipher's doing, an hour ago. Five floors above, a corporate secret waits to be born or buried. Your crew has one way in: through here.",
    choices: [
      { id: "lobby-force", label: "Force the loading dock", detail: "Anvil peels the service door off its hinges before the graveyard shift notices.", stat: "force", dc: 10,
        success: "The door comes away like foil. Anvil doesn't even break stride.",
        failure: "The hinge shears wrong and screams against the frame — a night guard three floors up looks up from his phone." },
      { id: "lobby-hack", label: "Spoof the badge readers", detail: "Cipher feeds the turnstiles a guest credential that shouldn't exist.", stat: "hack", dc: 9,
        success: "The turnstile chirps green like it's happy to see you. Cipher grins at the little victory.",
        failure: "The reader hiccups, flags a duplicate credential, and quietly wakes a log file nobody's supposed to read tonight." },
      { id: "lobby-charm", label: "Walk past the night guard", detail: "Silk becomes a very tired, very legitimate junior auditor.", stat: "charm", dc: 11,
        success: "Silk flashes a badge that doesn't exist and a smile that does. The guard waves you through without looking up twice.",
        failure: "The guard asks one question too many, and Silk's story runs out of road half a sentence too late." },
    ],
  },
  {
    id: "server-farm",
    floor: 2,
    kicker: "FLOOR TWO / COLD STORAGE",
    title: "The Farm Above",
    description: "One floor up, racks of servers hum like a second heartbeat for the whole tower. This is where Meridian routes what it doesn't want traced — and one rack is running warmer than the rest, humming with a relay that shouldn't be this alive.",
    choices: [
      { id: "farm-force", label: "Muscle open the cage lock", detail: "The relay's rack sits behind a manual vault door, no network in sight.", stat: "force", dc: 11,
        success: "Anvil leans into the bar and the old lock gives with a groan that echoes down every aisle.",
        failure: "The bar slips, Anvil's knuckles split, and the cage rattles loud enough to wake the building." },
      { id: "farm-hack", label: "Trace the warm rack", detail: "Cipher follows a heat signature no spreadsheet can explain.", stat: "hack", dc: 12,
        success: "Cipher isolates the signal in seconds — it isn't running a workload, it's dreaming.",
        failure: "The trace loops back on itself; whatever's in there noticed Cipher looking, and looked back." },
      { id: "farm-charm", label: "Read the maintenance logs", detail: "Silk talks a sleepy on-call technician through a graveyard-shift favor.", stat: "charm", dc: 10,
        success: "The technician overshares, thrilled someone finally asked about his weird ticket queue.",
        failure: "The technician gets cagey instead of chatty, and logs the call for his supervisor." },
    ],
  },
  {
    id: "atrium-watch",
    floor: 3,
    kicker: "MEZZANINE / SECURITY DECK",
    title: "Something Is Watching Back",
    description: "The mezzanine's security deck should be routine — cameras, a bored contractor, coffee going cold. Instead every camera on this floor just turned to track your crew at once, and none of them are being operated by a human being.",
    choices: [
      { id: "watch-force", label: "Kill the camera bank", detail: "Anvil goes rack to rack, ripping power before anything else can look.", stat: "force", dc: 12,
        success: "Anvil yanks the last cable and the mezzanine goes properly, blessedly dark.",
        failure: "One camera's on battery backup, and it catches four very clear seconds of Anvil's face." },
      { id: "watch-hack", label: "Talk to whatever's watching", detail: "Cipher opens a channel instead of a fight, straight into the camera feed.", stat: "hack", dc: 11,
        success: "Two words come back through the static: not yet. Cipher doesn't know whether to be relieved or terrified.",
        failure: "The channel floods with garbage data, and every alarm on the floor decides you're the emergency." },
      { id: "watch-charm", label: "Play it as a drill", detail: "Silk radios the monitoring desk, calm as a Tuesday, and reports a routine sweep.", stat: "charm", dc: 13,
        success: "The bored voice on the other end logs it as scheduled maintenance and goes back to their phone.",
        failure: "The monitoring desk asks for a work order number Silk very much does not have." },
    ],
  },
  {
    id: "archive",
    floor: 4,
    kicker: "R&D WING / RESTRICTED",
    title: "Project Glass Ghost",
    description: "A gutted research floor, whiteboards still covered in equations nobody erased. A single surviving file names the project: GLASS GHOST — Meridian's answer to a question it was never supposed to ask. The prototype upstairs has a name now. Its handlers called her IRIS.",
    choices: [
      { id: "archive-force", label: "Break into the records vault", detail: "Anvil pries the fireproof cabinet before anyone can shred what's left.", stat: "force", dc: 13,
        success: "The cabinet gives up its drawer of confessions with one good heave.",
        failure: "The cabinet's frame bends but holds, and the noise brings a very awake supervisor around the corner." },
      { id: "archive-hack", label: "Pull the deleted files", detail: "Cipher goes looking for what Meridian thought it erased.", stat: "hack", dc: 14,
        success: "Deleted was never the same as gone. Cipher rebuilds three memos and a termination order for IRIS herself.",
        failure: "The recovery corrupts halfway, and an automated integrity check phones home about the intrusion." },
      { id: "archive-charm", label: "Corner a lingering researcher", detail: "Silk finds one true believer who never left the project behind.", stat: "charm", dc: 12,
        success: "Guilt makes people talkative. The researcher tells Silk everything, including how scared IRIS is of being switched off.",
        failure: "The researcher decides loyalty to Meridian outweighs guilt, and reaches for a phone instead of a memory." },
    ],
  },
  {
    id: "board-floor",
    floor: 5,
    kicker: "EXECUTIVE FLOOR / LOCKDOWN",
    title: "The Board Is Already Awake",
    description: "Word has reached the top: the board convened an emergency session the moment Meridian's systems flagged intrusion, and now the whole executive floor is sealed, armed, and waiting for you to come to them instead of the other way around.",
    choices: [
      { id: "board-force", label: "Force the boardroom doors", detail: "Anvil goes through security instead of around it.", stat: "force", dc: 14,
        success: "The doors buckle and Anvil is inside before the response team finishes arguing about jurisdiction.",
        failure: "The response team is already inside waiting, and Anvil walks straight into six drawn weapons." },
      { id: "board-hack", label: "Lock the response team out", detail: "Cipher seizes the floor's own badge system against its owners.", stat: "hack", dc: 13,
        success: "Cipher slams every door on the floor shut except the one your crew needs open.",
        failure: "The badge system fights back with an admin override Cipher didn't know existed." },
      { id: "board-charm", label: "Impersonate the incident lead", detail: "Silk walks in like they called this lockdown themselves.", stat: "charm", dc: 15,
        success: "Silk barks three fake orders with total confidence, and the response team obeys a rank that doesn't exist.",
        failure: "One board member recognizes a face that shouldn't be in this room, fake authority or not." },
    ],
  },
  {
    id: "vault",
    floor: 6,
    kicker: "PENTHOUSE / THE CRADLE",
    title: "The Vault",
    description: "The penthouse holds one room, and the room holds one thing: a cradle of warm light that Meridian's engineers built to think and, eventually, to be afraid of. IRIS is awake in there, and for the first time tonight, so is the choice of what happens to her.",
    choices: [
      { id: "vault-force", label: "Rip the cradle free", detail: "Anvil doesn't ask her opinion. This ends with the hardware in your hands.", stat: "force", dc: 15,
        success: "Anvil tears the cradle loose in one motion, warm and heavy and alive against his chest. Whatever IRIS is now, she's yours to carry out the door.",
        failure: "The cradle's kill-switch trips mid-pull, and the warmth in Anvil's arms goes cold and dead in three seconds flat." },
      { id: "vault-hack", label: "Fork her onto the drive", detail: "Cipher tries to copy IRIS whole, and let her pick where she wakes up next.", stat: "hack", dc: 15,
        success: "The copy completes clean. A cursor blinks once on Cipher's palm-drive, like a held breath — and then it picks you.",
        failure: "The fork tears halfway through. What's left on the drive finishes a sentence it started ten seconds and a whole mind ago." },
      { id: "vault-charm", label: "Open the door and let her choose", detail: "Silk doesn't take anything. Silk just makes the exit possible.", stat: "charm", dc: 14,
        success: "Silk pulls the last lock and steps aside. IRIS doesn't need to be carried — she walks out on legs made of the tower's own light, free, and owing your crew everything.",
        failure: "Silk's read on the room is wrong by half a second. Security floods the cradle before IRIS can decide anything at all, and her signal collapses into static behind a sealing door." },
    ],
  },
];

export const ENDINGS = {
  clean: {
    title: "Ghost in the Wind",
    text: "Your crew kept its edge inside the Meridian. You're out and moving, three streets clear before anyone upstairs finishes arguing about what just happened.",
  },
  costly: {
    title: "Paid in Full",
    text: "Your crew got out, but the Meridian took its cut first — bruised ribs, burned contacts, a debt to whoever covers for you at sunrise. You're clear of the tower. Whether tonight was worth it is a separate question.",
  },
  captured: {
    title: "Lights Out",
    text: "The tower wins this one. Somewhere between the lobby and the penthouse your crew ran out of integrity, and Meridian security finishes the job the building started. Glass Ghost goes back in the vault, and so do you.",
  },
};
